# permissions for end users to edit ghosts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: ghost-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: operator-tutorial
    app.kubernetes.io/part-of: operator-tutorial
    app.kubernetes.io/managed-by: kustomize
  name: ghost-editor-role
rules:
- apiGroups:
  - blog.example.com
  resources:
  - ghosts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - blog.example.com
  resources:
  - ghosts/status
  verbs:
  - get
